### ISSUE TITLE
Ability for members to upload an image to prove voting entitlement.

### ISSUE THREAD

**Issue by GeertJohan** [GeenPeil/stem#12]

**Comment by pepijnvanleeuwen** [comment]
I'd like to pick up this task. Any additional recommedations about file upload constraints, e.g. maximum dimensions, file size and mime type (png/jpg)?

**Comment by GeertJohan** [comment]
I think we should accept both png and jpg with an upper upload size of 10MB. Please verify image integrity after upload by decoding and re-encoding with the golang `image` package. Lets not add a dimensions limit now, eventually we can add a minimum dimensions requirement to avoid users uploading postage stamps ;)

**Comment by GeertJohan** [comment]
For now, lets store image on-disk. I'll be able to add the encryption layer later. (Although, if you want you could give that a shot, but it's not perse in scope for this issue).

**Comment by wilgert** [comment]
Maybe we can use TransIP Stack for storing the images, that is cloudstorage
in The Netherlands.

2017-01-19 12:28 GMT+01:00 Geert-Johan Riemer <notifications@github.com>:

**Comment by riesvriend** [comment]
Ik verwacht dat je ook PDF moet ondersteunen. Smartphones geven een png, scanners doen vaak een PDF-naar-email als output.

**Comment by GeertJohan** [comment]
@riesvriend Dat lijkt inderdaad een goede toevoeging. Laten we dat doen.

**Comment by GeertJohan** [comment]
Issue has been moved to https://geenpeil.atlassian.net/
