### ISSUE TITLE
Fix Travis building of arib and opstelten.

### ISSUE THREAD

**Issue by GeertJohan** [GeenPeil/stem#14]

**Comment by wilgert** [comment]
@GeertJohan I can pick this up

**Comment by GeertJohan** [comment]
That would be great! Feel free to assign yourself and put it "In progress" over at https://github.com/GeenPeil/stem/projects/2#card-1395042

**Comment by wilgert** [comment]
What exactly is not working. As this looks like it is doing something and it's exiting correctly: https://travis-ci.org/GeenPeil/stem/builds/192849697

**Comment by GeertJohan** [comment]
Correct, but that is only because I've dissabled the npm tasks.
https://github.com/GeenPeil/stem/blob/master/Makefile

**Comment by GeertJohan** [comment]
Failing build with npm jobs enabled: https://travis-ci.org/GeenPeil/stem/builds/192675599

**Comment by GeertJohan** [comment]
Issue has been moved to https://geenpeil.atlassian.net/
